## HaGeZi Pro Mini
https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/pro.mini-onlydomains.txt
## 217heidai/adblockfilters (only CN)
https://raw.githubusercontent.com/217heidai/adblockfilters/main/rules/adblockhostslite.txt
## HaGeZi Threat Intelligence Feeds (mini)
https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/tif.mini-onlydomains.txt
## Online Malicious URL Blocklist
https://curbengh.github.io/malware-filter/urlhaus-filter-hosts.txt
## ddg-blocklist (DuckDuckGo tracker blocklist, own project)
https://github.com/hydroakri/ddg-blocklist/releases/latest/download/blocklist-all.txt
